In [4]:
import numpy as np
array=np.array([1,2,3])
print(array)
print(type(array));
print(array.shape)


[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [5]:
print(array[2])

3


In [8]:
print(array[0])

np.int64(1)

In [11]:
array[2]=5
array

array([1, 2, 5])

In [13]:
array2=np.array([[1,2,3],[3,4,5]])
array2

array([[1, 2, 3],
       [3, 4, 5]])

In [16]:
print(array2[1][2])
print(array2.shape)

5
(2, 3)


In [17]:
array2[1,2]

np.int64(5)

In [20]:
array2[1,-2]

np.int64(4)

In [21]:
arr2=np.array(['china', 'pakistan', 'india'])
print(arr2)

['china' 'pakistan' 'india']


In [32]:
arr3=np.arange(9,20)
arr3






array([0])

In [37]:
arr5=np.arange(0,20,2)
arr5
arr5=np.linspace(0,10,20)
arr5


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [39]:
rk=np.random.rand(10)
rk

array([0.49711944, 0.42147107, 0.25679144, 0.12138046, 0.60426296,
       0.11192975, 0.06726412, 0.32289687, 0.49346742, 0.34274144])

In [46]:
rohit=np.random.rand(3,4)
rohit


array([[0.11847294, 0.83451286, 0.89824352, 0.116071  ],
       [0.43240609, 0.88350206, 0.03926437, 0.44502761],
       [0.91182211, 0.23428409, 0.03408624, 0.9356012 ]])

In [45]:
rohit1=np.random.rand()
rohit1

0.8463707759101547

In [50]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])
np.intersect1d(arr1,arr2)

array([4, 5])